# Generated by Django 6.0.4 on 2026-05-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
